version: "3.7"

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=${SQL_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "${SQL_PORT}:1433"

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:27017

  migrations:
    build:
      context: ./api
      dockerfile: Migrations.Dockerfile
    depends_on:
      - sqldata

  api:
    build: ./api
    restart: always
    ports:
      - "5079:5079"
    depends_on:
      - sqldata
      - mongodb
      - migrations

  dashboard:
    build: ./dashboard
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - api
